version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '[%(asctime)s.%(msecs)03d][%(levelname)s][%(name)s]: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: default.log
  ui:
    class: simple_python_app_qt.qml_application.UiLogHandler
    level: INFO
    formatter: simple
loggers:
  main:
    level: INFO
    handlers: [file, console, ui]
    propagate: no
root:
  level: INFO
  handlers: [file, console, ui]
